export const AUTH_LOGIN = 'AUTH_LOGIN';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_SUCCESS_NAVIGATE = 'AUTH_LOGIN_SUCCESS_NAVIGATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
export const AUTH_FORGET_PASSWORD = 'AUTH_FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'AUTH_FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILURE = 'AUTH_FORGET_PASSWORD_FAILURE';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'AUTH_CHANGE_PASSWORD_FAILURE';



export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS = 'FETCH_PRODUCTS_BY_CATEGORY_SUCCESS';
export const FETCH_PRODUCTS_BY_CATEGORY_FAILURE = 'FETCH_PRODUCTS_BY_CATEGORY_FAILURE';
export const FETCH_USER_ADD_ADDRESS_SUCCESS = 'FETCH_USER_ADD_ADDRESS_SUCCESS';
export const FETCH_USER_ADD_ADDRESS_FAILURE = 'FETCH_USER_ADD_ADDRESS_FAILURE';
export const FETCH_USER_REQUEST_ADD_ADDRESS = 'FETCH_USER_REQUEST_ADD_ADDRESS';
export const FETCH_USER_REQUEST_DELETE_ADDRESS = 'FETCH_USER_DELETE_ADDRESS_SUCCESS';
export const FETCH_USER_DELETE_ADDRESS_SUCCESS = 'FETCH_USER_DELETE_ADDRESS_SUCCESS';
export const FETCH_USER_DELETE_ADDRESS_FAILURE = 'FETCH_USER_DELETE_ADDRESS_FAILURE';


export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const CLEAN_CART = 'CLEAN_CART';
export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';
export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';
export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAILURE = 'DELETE_CART_FAILURE';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';


export const FETCH_ADDRESSES_REQUEST = 'FETCH_ADDRESSES_REQUEST';
export const FETCH_ADDRESSES_SUCCESS = 'FETCH_ADDRESSES_SUCCESS';
export const FETCH_ADDRESSES_FAILURE = 'FETCH_ADDRESSES_FAILURE';

export const REMOVE_ADDRESS_REQUEST = 'REMOVE_ADDRESS_REQUEST';
export const REMOVE_ADDRESS_SUCCESS = 'REMOVE_ADDRESS_SUCCESS';
export const REMOVE_ADDRESS_FAILURE = 'REMOVE_ADDRESS_FAILURE';